### ISSUE TITLE
[Feature request] Add a command to list installed Visual C++ Redistributables

### ISSUE THREAD

**Issue by mlocati** [aaronparker/Install-VisualCRedistributables#18]
What about adding a command to list already installed Visual C++ Redistributables?

I'm creating a package that dinamically downloads and install other programs, each of them can require a different Visual C++ Redistributable version and architecture.

If we had such command, I could do something like

```powershell
$found = Get-InstalledVcRedist | Where {$_.Version -eq '2015' -and $_.Architecture -eq 'x64'}
If ($found -eq $null) {
    # Install the 2015/x64 Visual C++ Redistributable
}
```

**Comment by aaronparker** [comment]
I've been thinking about doing this, just haven't gotten back to it. Should the function just list what's installed on the current machine or compare with what's in the manifest (`Get-VcList`)?

The output of `Get-InstalledVcRedist` could be used to ensure that `Install-VcRedist` doesn't attempt to install a VcRedist that's already installed.

**Comment by mlocati** [comment]
Well, here's what I have in my mind (pseudocode):
```
If not installed vc-2015-x86 {
    Download setup of vc-2015-x86
    Try {
        Install vc-2015-x86
    }
    Finally {
        Delete setup of vc-2015-x86
    }
}
```

**Comment by aaronparker** [comment]
Added `Get-InstalledVcRedist` in v1.3.6.56
