### ISSUE TITLE
Import MDT Function

### ISSUE THREAD

**Issue by BronsonMagnan** [aaronparker/Install-VisualCRedistributables#22]
# Expected Behavior

I expect redist package marked as x86 architecture to run on the specified client platforms:
All x86 Windows 7 and Newer
All x64 Windows 7 and Newer

# Current Behavior

Only "All x86 Windows 7 and Newer" is selected instead.

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug by issuing the command using the `-Verbose` command.

```
Paste the verbose output from the command here
```

**_If it is not a bug, please remove the rest of this template._**

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Step 1
1. Step 2
1. Step 3 (and so on)

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* **VcRedist Version**: Use `Get-Module -ListAvailable VcRedist`
* **PowerShell Version**: Use `Get-PSVersion`
* **Operating System**:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by aaronparker** [comment]
I think I have x86 and x64 client platforms reversed - The x64 app is set to run on x64 and x86 platforms and the x86 app is set to run on x86 only.

**Comment by aaronparker** [comment]
Fixed in latest release via #23
