### ISSUE TITLE
Import-vcmdtapp creates MDT applications with client only OS filters

### ISSUE THREAD

**Issue by BronsonMagnan** [aaronparker/Install-VisualCRedistributables#33]
# Expected Behavior

If filters are to be used, they would allow for installation on server operating systems as well as reference images are created for xenapp/rds installations.

# Current Behavior

Filters on x86 apps create a filter for windows 7 x86 and up.
Filters on x64 apps create a filter for windows 7 x86 and up, and windows 7 x64 and up.

# Recommended Behavior
Add filter for Windows Server 10 x64 and up 

## Steps to Reproduce

Run against a server operating system in a client task sequence.

**Comment by BronsonMagnan** [comment]
Aaron, debugged this a bit on some other systems, and the problem actually is related to the "working directory" value that is created in the MDT application. The subfolder is not present in the path. I am not sure if the filters are a actually a problem anymore, but I have removed them during testing.

**Comment by chrisshearing** [comment]
it looks like this code was stripped out in commit e7b192f

 $dir = "$Publisher VcRedist\$($Vc.Release) $($Vc.ShortName) $($Vc.Architecture)"

it was used for
                    -WorkingDirectory ".\Applications\$dir" `
                    -DestinationFolder $dir `

destination folder was updated to

                    DestinationFolder       = "$Publisher VcRedist\$($Vc.Release) $($Vc.ShortName) $($Vc.Architecture)"

but working directory is still

                    WorkingDirectory        = ".\Applications\$dir"

So this needs updating to 

                    WorkingDirectory        = ".\Applications\$Publisher VcRedist\$($Vc.Release) $($Vc.ShortName) $($Vc.Architecture)"

at the moment none of the imported applications in MDT work, they fail to install with file not found as the working directory is just ".\Applications\"

**Comment by aaronparker** [comment]
This should now be fixed in the latest development commit and will make it into the latest release.

**Comment by aaronparker** [comment]
Fixed in v1.4.2.85; commit 7004e11b4e71aa6b84834d1977414b157546cc8d
