### ISSUE TITLE
Delete Version 2015 from XML

### ISSUE THREAD

**Issue by frankfde** [aaronparker/Install-VisualCRedistributables#8]
Hi,
VCRedist 2017 is an update to version2015. You install 2015 and overwrite same seconds later. :)
Delete it from the VisualCRedistributablesSupported.xml

LogFile if you try to install 2015 if 2017 is installed. 
[1FB8:0CA0][2017-08-17T07:19:09]e000: Error 0x80070666: Cannot install a product when a newer version is installed.

Regards
Frank

**Comment by aaronparker** [comment]
I'm going via this article for supported versions: [https://support.microsoft.com/en-au/help/2977003/the-latest-supported-visual-c-downloads](https://support.microsoft.com/en-au/help/2977003/the-latest-supported-visual-c-downloads). 

I know 2017 is an upgrade to the 2015 version, but wanted to align with the supported versions.

**Comment by TimMangan** [comment]
Yes, please keep it.  With App-V Packaging, we would install 2015 without 2017 for certain installers to be happy, then deploy 2017 on images.

**Comment by aaronparker** [comment]
Thanks Tim. I think the right approach is to keep all of the installers - there's no reason anyone couldn't edit the XML after downloading it from here.
